// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/skywalking_cola component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("skywalking_cola")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/skywalkingreceiver-cola"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
	TracesStability  = component.StabilityLevelBeta
)
